### ISSUE TITLE
Quickplay Keybinding

### ISSUE THREAD

**Issue by PynkLemonade** [bugfroggy/Quickplay2.0#107]
Hi bug,  I have apparently found a bug and was told by asbyth to get in touch with you in order to resolve it. Essentially, the queuing/quickplay feature does not work properly in that I can keybind a game but it will not stay bound and brings up a strange menu when I click the key. Thank you!

[Screen Recording of Issue](https://drive.google.com/file/d/1JvCA3C7uW0aXuQGBdqK1zASBNBO1vjwP/view?usp=sharing)

**Comment by robere2** [comment]
The menu in the video you sent is not part of Quickplay. Are you sure your `k` key is not bound to something else as well?

**Comment by PynkLemonade** [comment]
Apparently it was. I am sorry for wasting your time. It was a dumb mistake to make, but I appreciate your helping me fix it.
