### ISSUE TITLE
Quickplay 2.0 Crashing the game on any server i go to except on hypixel

### ISSUE THREAD

**Issue by SangeloDev** [bugfroggy/Quickplay2.0#113]
As the title says, I can't join any server with the mod installed except Hypixel. This is really annoying because I play on a lot of servers. Is there any fix for this or do I have to live with it?

**Comment by robere2** [comment]
Sorry I did not notice this earlier. Do you have a crash report?

**Comment by SangeloDev** [comment]
I fixed it, looks like VanillaEnhancements was the problem. I also couldn't click on links in chat. So if anyone else has the same issue, here's the reason
