### ISSUE TITLE
{"server":"miniXXXX" messages are spamming in  the chat

### ISSUE THREAD

**Issue by najoan125** [bugfroggy/Quickplay2.0#142]
I using Quickplay 2.0.6 1.12.2.
When I moving a server, {"server":"miniXXXX" messages are spamming in the chat
![spamming messages example image](https://user-images.githubusercontent.com/68422289/125321538-c1fb0900-e377-11eb-8b74-9aab639cb82d.png)

So I looked at the code and found the answer.

LocrawWrapper.java
82 Line: !event.isCanceled() &&
(Don't erase the old code.)

This solved the bug.
but This code is not perfect(Errors are often found in logs.)

(I'm Korean. I used Translator. I ask for your understanding.)

**Comment by robere2** [comment]
Fixed in 2.0.7
