### ISSUE TITLE
Possible enhancement for the config menu.

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#2]
I'd like to suggest adding some padding to the darkened background in the Quickplay Config menu. At first, I was wondering if the menu had more options underneath or had clipped outside of the game. Just a small aesthetical thing. :cat: 

![image](https://user-images.githubusercontent.com/26250962/36626704-51724b64-192f-11e8-9f1a-2819b0b242b2.png)
       Some padding here! ^

**Comment by robere2** [comment]
Seems like your screen is _just_ the right size to where this is an issue. I will see if there's anything I can do.

**Comment by Snuggle** [comment]
`1920x1080`, if you need that. :smiley_cat:
It's also worth to note that I have polybar at the top, which makes my game window slightly smaller.
