### ISSUE TITLE
Could we please move the Quickplay menu around?

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#3]
At `0.52` scale, the menu is in the way of my heath-bar and boss-bar. I'd love to move it down a tiny bit. Perhaps right-click + drag? ALT + Drag? You could add a small tool-tip in the corner or something to show people how to move it. :cat: 

![image](https://user-images.githubusercontent.com/26250962/36626909-e5476e2a-1932-11e8-9119-79317dadd06e.png)

**Comment by robere2** [comment]
Depending on if it looks ugly or not, perhaps I could make it so icons center vertically if they all fit on the screen. Would that work? If not or if it just looks ugly I can look into possibly making it a hidden config item. That way users who need it can use it but it's not so confusing for people who don't care. Will see.

**Comment by Snuggle** [comment]
Centering vertically would look nice if the scoreboard didn't exist... Hypixel has that basically everywhere, though, so I don't think that would look nice, unless you can hide the scoreboard while in the QP menu. :thinking:

Yeah, maybe adjustable padding in the config? I feel like it'd be too much work to move/resize the menu and have it automatically wrap inside of an invisible "safe" area. Up to you, though. c:

**Comment by robere2** [comment]
You can now do this.

1. `/qp config`
2. Click "Open Folder"
3. Open `settings.json` in your text editor of choice.
4. Edit `mainMenuYPadding` to the number of units you'd like.

**Comment by Snuggle** [comment]
Dang. Thank you! c:
