### ISSUE TITLE
Allow people to click the game's name?

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#4]
You can't highlight/click text. Only the icons themselves. I've tried to join Bedwars a couple times, just to wonder... "Why did it not work?! Oh, I clicked the text."

This'd be a nice usability enhancement. :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/26250962/36627201-400e38a8-1937-11e8-9f1a-bcc02901b703.png)
![image](https://user-images.githubusercontent.com/26250962/36627207-5a4f162e-1937-11e8-94f4-ede55dba785c.png)

**Comment by robere2** [comment]
This is planned but requires some rewriting.

**Comment by Snuggle** [comment]
Yaaay! Thank you! I'm assuming this'll be in QuickPlay2.1 or something? :yum:

**Comment by robere2** [comment]
Quickplay 2.0.0-beta.2
