### ISSUE TITLE
ability to change quickplay gui keybind in controls 

### ISSUE THREAD

**Issue by Eyad500** [bugfroggy/Quickplay2.0#40]
so before i started using quickplay 2.0 i had R as one of my hotbar keys but after that i couldnt use it because the gui opens then i searched for a way to change the quickplay mod key in controls but i couldnt find it

**Comment by robere2** [comment]
You can change your keybinds by doing `/qp keybinds`. You can also add new keybinds by right-clicking games or modes and then clicking "Bind to key...".
