### ISSUE TITLE
"Blur GUI Backgrounds" config option

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#5]
The `Blur GUI Backgrounds` option doesn't actually seem to do its function, even after a restart.

The background seems to always stay blurred, even when it's set to `FALSE`.
![image](https://user-images.githubusercontent.com/26250962/36627309-dae18f28-1938-11e8-8ad1-708954d79981.png)
**Restarted Minecraft, just in case**
![image](https://user-images.githubusercontent.com/26250962/36627340-381a957c-1939-11e8-91d8-e2df57d0b2d5.png)

**Comment by robere2** [comment]
Do you have any other mods installed? If you have a mod that blurs other GUI backgrounds like inventories, then my setting will be ignored.

**Comment by robere2** [comment]
Closing this due to lack of information. Re-open if you have any more information about the issue.
