### ISSUE TITLE
Do glyphs allow IP address capturing?

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#59]
If you can put in custom image URL’s and the images are fetched clientside (not fetched through a proxy etc.), it’d be possible to setup a web server that’s hosting an image but logging any IP addresses that make a request for that image. 

With how the Minecraft community is, I could see this as being a potential security flaw. I believe the easiest solution is to only allow “imgur.com/[...]” as a valid image URL.

Most other services (Like Discord had to do a few years ago) proxy any image requests through their own CDN, which means that the requests are coming from Discord and not any user directly.

**Comment by robere2** [comment]
When a user sets their glyph, the URL submitted is requested and then re-uploaded to Imgur for security checks and distribution. The original URL is queried twice and then never used again, as the content is hosted elsewhere. The original URL is not distributed to clients, or even stored, afterwards.
If this doesn't clear up your concern then please clarify.  Thanks :)

**Comment by robere2** [comment]
In the future I would like to host images locally to remove the involvement of third parties but that requires additional security that is currently handled by Imgur.

**Comment by Snuggle** [comment]
Ah, huh. The URL requesting process is manual?

**Comment by robere2** [comment]
Glyphs are set up and rehosted automatically through their API: https://apidocs.imgur.com/
