### ISSUE TITLE
Typing commands without the slash runs them

### ISSUE THREAD

**Issue by robere2** [bugfroggy/Quickplay2.0#65]
If you type a Quickplay command without a slash, it still runs the command. This is the case for all commands, including: `qp`, `hub`, `quickplaylobby`, `leave`, etc. Parameters can be sent as well.

**Comment by P250** [comment]
yeah I noticed this on one of my mods - do you happen to have a fix for this?

**Comment by robere2** [comment]
@P250 I did some research a while back and I believe this has to do with implementing the wrong class. I'm not sure if it was always this way or Forge changed it.
http://www.minecraftforge.net/forum/topic/37000-commands-trigger-without-a-slash/
http://www.minecraftforge.net/forum/topic/64820-command-executes-without-backslash/
I would either implement another class OR I think it's possible to just add a slash to the beginning of all the command names/aliases.

**Comment by P250** [comment]
alright, thank you!

**Comment by P250** [comment]
> @P250 I did some research a while back and I believe this has to do with implementing the wrong class. I'm not sure if it was always this way or Forge changed it.
> http://www.minecraftforge.net/forum/topic/37000-commands-trigger-without-a-slash/
> http://www.minecraftforge.net/forum/topic/64820-command-executes-without-backslash/
> I would either implement another class OR I think it's possible to just add a slash to the beginning of all the command names/aliases.

Also if you have 2 mods that implement ICommand the commands for one mod won't work.. I've no idea why, anyway I guess you have to use another class like you said.

**Comment by robere2** [comment]
Closing because this is a 1.8.9 bug and it makes more sense for a user to download a separate fix. i.e. https://sk1er.club/mods/patcher
