### ISSUE TITLE
Hypixel Matcher

### ISSUE THREAD

**Issue by tomocrafter** [bugfroggy/Quickplay2.0#7]
66.70.179.180 <- This ip address also leads to hypixel.

**Comment by robere2** [comment]
Thanks but I'm no longer adding specific IP addresses. I've added the most popular ones as well as a backup system that tries to check for a /whereami response, the MOTD, the tab list header & footer, and the server icon. If someone manages to bypass all of these checks then they should probably simply just log on with an official IP.
